"""Seed demo data on startup if the verify schema is empty."""
import json
from datetime import timezone, datetime

DEMO_MATTERS = [
    {
        "id": 1,
        "subject": "Robert J. Henderson",
        "ref": "HF-2024-0847",
        "type": "bankruptcy",
        "type_label": "Bankruptcy",
        "matter_date": "14 Mar 2024",
        "assigned_to": "Michael Anderson",
        "notes": "Director of Henderson Packaging Pty Ltd. Voluntary administration.",
        "exposure": "HIGH",
        "att": "red",
        "att_flag": "🔴 High Exposure",
        "last_run": "20 Mar 2026 · 09:14",
        "doc_count": 7,
        "analysed": True,
        "las_score": 84,
        "las_verdict": "DO FIRST",
        "las_verdict_cls": "high",
        "las_reason": "Crypto inflows in 90-day preference window · $165k income gap · High recovery probability via US subpoena.",
    },
    {
        "id": 2,
        "subject": "Quantum Logistics Pty",
        "ref": "HF-2024-0691",
        "type": "bankruptcy",
        "type_label": "Bankruptcy",
        "matter_date": "08 Nov 2023",
        "assigned_to": "Sarah Chen",
        "notes": "Multiple exchange accounts detected. Structuring pattern in preference period.",
        "exposure": "HIGH",
        "att": "red",
        "att_flag": "🔴 High Exposure",
        "last_run": "10 Mar 2026 · 11:20",
        "doc_count": 12,
        "analysed": True,
        "las_score": 77,
        "las_verdict": "DO FIRST",
        "las_verdict_cls": "high",
        "las_reason": "Structuring pattern in preference period · Cross-border transfers · Multiple exchange accounts.",
    },
    {
        "id": 3,
        "subject": "Marchetti Family Trust",
        "ref": "HF-2025-0112",
        "type": "family_law",
        "type_label": "Family Law",
        "matter_date": "02 Jun 2025",
        "assigned_to": "Sarah Chen",
        "notes": "Missing 2023 statements. Rental income not disclosed in separation agreement.",
        "exposure": "MEDIUM",
        "att": "amber",
        "att_flag": "🟡 Documents Missing",
        "last_run": "19 Mar 2026 · 14:32",
        "doc_count": 4,
        "analysed": True,
        "las_score": 61,
        "las_verdict": "REVIEW NEXT",
        "las_verdict_cls": "mid",
        "las_reason": "Mortgage and rental signals · Income gap moderate · Missing 2023 statements may change score.",
    },
    {
        "id": 4,
        "subject": "Thornton v Thornton",
        "ref": "HF-2025-0334",
        "type": "family_law",
        "type_label": "Family Law",
        "matter_date": "20 Jan 2025",
        "assigned_to": "James Okafor",
        "notes": "Straightforward matter. Income consistent across all sources.",
        "exposure": "LOW",
        "att": "green",
        "att_flag": "",
        "last_run": "15 Mar 2026 · 16:05",
        "doc_count": 6,
        "analysed": True,
        "las_score": 22,
        "las_verdict": "LOW URGENCY",
        "las_verdict_cls": "low",
        "las_reason": "Limited signals · No crypto activity · Income gap within normal range.",
    },
]

# Pre-computed results keyed by matter index (0-based, matched to DEMO_MATTERS order)
DEMO_RESULTS = {
    1: {
        "matter_id": 1,
        "run_at": "2026-03-20T09:14:00+00:00",
        "exposure": "HIGH",
        "att": "red",
        "att_flag": "🔴 High Exposure",
        "las": {
            "score": 84,
            "verdict": "DO FIRST",
            "verdict_cls": "high",
            "reason": "Crypto inflows in 90-day preference window · $165k income gap · High recovery probability via US subpoena.",
            "components": [
                {"label": "Signal Severity",    "val": 38, "max": 40},
                {"label": "Timing / Urgency",   "val": 22, "max": 25},
                {"label": "Financial Gap",      "val": 16, "max": 20},
                {"label": "Recovery Potential", "val":  8, "max": 15},
            ],
        },
        "signals": [
            {"name": "Crypto Exchange Activity",     "cat": "ASSET · CONVERSION",      "status": "detected", "count": 18, "amount": "$87,400"},
            {"name": "Crypto Payment Gateways",      "cat": "CONVERSION",               "status": "detected", "count":  3, "amount": "$22,100"},
            {"name": "Mortgage Servicer Activity",   "cat": "ASSET",                    "status": "detected", "count": 12, "amount": "$38,400"},
            {"name": "Gambling Platforms",           "cat": "CONVERSION · OBFUSCATION", "status": "detected", "count":  7, "amount":  "$4,850"},
            {"name": "Luxury Asset Merchants",       "cat": "ASSET",                    "status": "detected", "count":  5, "amount": "$31,200"},
            {"name": "Travel Vendors",               "cat": "FLOW · LIFESTYLE",         "status": "detected", "count":  9, "amount": "$14,200"},
            {"name": "Property Tax Authorities",     "cat": "ASSET",                    "status": "detected", "count":  2, "amount":  "$3,400"},
            {"name": "Storage Facilities",           "cat": "ASSET",                    "status": "possible", "count":  0, "amount": None},
            {"name": "Second Household Indicators",  "cat": "ASSET",                    "status": "possible", "count":  0, "amount": None},
            {"name": "Structuring / Cash Behaviour", "cat": "OBFUSCATION",              "status": "possible", "count":  0, "amount": None},
            {"name": "Recurring Unnamed Transfers",  "cat": "FLOW · OBFUSCATION",       "status": "possible", "count":  0, "amount": None},
            {"name": "DeFi Platforms",               "cat": "ASSET · CONVERSION",       "status": "none",     "count":  0, "amount": None},
            {"name": "Rental Platforms",             "cat": "ASSET · FLOW",             "status": "none",     "count":  0, "amount": None},
            {"name": "Gold & Precious Metals",       "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Gift Card / Prepaid",          "cat": "OBFUSCATION",              "status": "none",     "count":  0, "amount": None},
            {"name": "Cross-Border Value Transfer",  "cat": "FLOW",                     "status": "none",     "count":  0, "amount": None},
        ],
        "intel": [
            {
                "cat": "ASSET · CONVERSION", "cat_cls": "asset",
                "title": "Crypto Exchange Activity",
                "narrative": "18 transactions totalling $87,400 to Coinbase (12, $52,100) and Kraken (6, $35,300). 14 transactions totalling $61,200 occurred within the 90-day preference window.",
                "rec": "High Recovery", "rec_cls": "high",
                "tier": "Tier 1 — Global Leaders",
                "path": "Coinbase: Standard US subpoena (18 U.S.C. § 2703). Well-documented compliance — expect KYC records, transaction history, wallet addresses. Est. 30–60 days. Kraken: US-regulated, same route. File preservation letter immediately.",
            },
            {
                "cat": "ASSET", "cat_cls": "asset",
                "title": "Undisclosed Mortgage — Possible Second Property",
                "narrative": "12 regular Westpac Mortgage payments, $38,400 total. No corresponding property in the bankruptcy petition. Payment pattern consistent with an investment property or second residence.",
                "rec": "High Recovery", "rec_cls": "high",
                "tier": "Domestic Asset",
                "path": "Immediate land title search. Cross-reference state revenue office for stamp duty. Subpoena Westpac for loan details, security address, account holder.",
            },
            {
                "cat": "CONVERSION · OBFUSCATION", "cat_cls": "obfuscation",
                "title": "Gambling Platform Activity",
                "narrative": "7 transactions ($4,850) across Sportsbet and Ladbrokes. Net position may differ — withdrawal history may reveal secondary accounts or undisclosed winnings.",
                "rec": "Medium Recovery", "rec_cls": "medium",
                "tier": "Licensed AU Operators",
                "path": "Formal request to Sportsbet and Ladbrokes for full account history, KYC records, current balance, and withdrawal destination accounts.",
            },
            {
                "cat": "OBFUSCATION", "cat_cls": "obfuscation",
                "title": "Structuring — Possible",
                "narrative": "Cash withdrawals clustering below reporting thresholds across a 6-month window. Pattern is consistent with deliberate structuring to avoid transaction records.",
                "rec": "Low Recovery", "rec_cls": "low",
                "tier": "Behavioural Signal",
                "path": "Document for trustee report. Subpoena ATM records to establish withdrawal locations — may identify secondary addresses or associates.",
            },
        ],
        "verify_plus_teaser": {
            "available": True,
            "verdict": "YES — PURSUE",
            "recovery_estimate": "$247,400 identified",
            "priority_action": "File preservation letter: Coinbase + Westpac subpoena",
        },
    },
    2: {
        "matter_id": 2,
        "run_at": "2026-03-10T11:20:00+00:00",
        "exposure": "HIGH",
        "att": "red",
        "att_flag": "🔴 High Exposure",
        "las": {
            "score": 77,
            "verdict": "DO FIRST",
            "verdict_cls": "high",
            "reason": "Structuring pattern in preference period · Cross-border transfers · Multiple exchange accounts.",
            "components": [
                {"label": "Signal Severity",    "val": 35, "max": 40},
                {"label": "Timing / Urgency",   "val": 20, "max": 25},
                {"label": "Financial Gap",      "val": 14, "max": 20},
                {"label": "Recovery Potential", "val":  8, "max": 15},
            ],
        },
        "signals": [
            {"name": "Crypto Exchange Activity",     "cat": "ASSET · CONVERSION",      "status": "detected", "count": 22, "amount": "$112,500"},
            {"name": "Crypto Payment Gateways",      "cat": "CONVERSION",               "status": "none",     "count":  0, "amount": None},
            {"name": "Mortgage Servicer Activity",   "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Gambling Platforms",           "cat": "CONVERSION · OBFUSCATION", "status": "none",     "count":  0, "amount": None},
            {"name": "Luxury Asset Merchants",       "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Travel Vendors",               "cat": "FLOW · LIFESTYLE",         "status": "detected", "count":  4, "amount":  "$8,200"},
            {"name": "Property Tax Authorities",     "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Storage Facilities",           "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Second Household Indicators",  "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Structuring / Cash Behaviour", "cat": "OBFUSCATION",              "status": "detected", "count":  9, "amount": "$43,200"},
            {"name": "Recurring Unnamed Transfers",  "cat": "FLOW · OBFUSCATION",       "status": "detected", "count": 14, "amount": "$67,800"},
            {"name": "DeFi Platforms",               "cat": "ASSET · CONVERSION",       "status": "possible", "count":  0, "amount": None},
            {"name": "Rental Platforms",             "cat": "ASSET · FLOW",             "status": "none",     "count":  0, "amount": None},
            {"name": "Gold & Precious Metals",       "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Gift Card / Prepaid",          "cat": "OBFUSCATION",              "status": "possible", "count":  0, "amount": None},
            {"name": "Cross-Border Value Transfer",  "cat": "FLOW",                     "status": "detected", "count":  6, "amount": "$38,100"},
        ],
        "intel": [
            {
                "cat": "ASSET · CONVERSION", "cat_cls": "asset",
                "title": "Crypto Exchange Activity",
                "narrative": "22 transactions totalling $112,500 across Binance (14, $78,300) and multiple smaller exchanges (8, $34,200). Activity spans the full preference period.",
                "rec": "High Recovery", "rec_cls": "high",
                "tier": "Tier 1 — Global Leaders",
                "path": "Binance has AU operations subject to AUSTRAC reporting. File preservation request immediately. For offshore holdings, pursue via MLAT or voluntary disclosure.",
            },
            {
                "cat": "OBFUSCATION", "cat_cls": "obfuscation",
                "title": "Structuring Pattern Detected",
                "narrative": "9 cash withdrawals totalling $43,200 structured below the $10,000 reporting threshold across a 4-month window. Pattern is statistically inconsistent with normal business cash handling.",
                "rec": "Low Recovery", "rec_cls": "low",
                "tier": "Behavioural Signal",
                "path": "Report to AUSTRAC if not already done. Subpoena ATM CCTV and records. Document pattern for preference period claim.",
            },
            {
                "cat": "FLOW", "cat_cls": "flow",
                "title": "Cross-Border Value Transfers",
                "narrative": "6 international transfers totalling $38,100 via Wise and OFX to accounts in Singapore and Hong Kong. No disclosed foreign business interests.",
                "rec": "Medium Recovery", "rec_cls": "medium",
                "tier": "Remittance Operators",
                "path": "Subpoena Wise and OFX for recipient details and beneficiary identity. Initiate MLAT request for Singapore/HK account information.",
            },
        ],
        "verify_plus_teaser": {
            "available": True,
            "verdict": "YES — PURSUE",
            "recovery_estimate": "$231,700 identified",
            "priority_action": "Binance AUSTRAC request + Wise / OFX subpoena",
        },
    },
    3: {
        "matter_id": 3,
        "run_at": "2026-03-19T14:32:00+00:00",
        "exposure": "MEDIUM",
        "att": "amber",
        "att_flag": "🟡 Documents Missing",
        "las": {
            "score": 61,
            "verdict": "REVIEW NEXT",
            "verdict_cls": "mid",
            "reason": "Mortgage and rental signals · Income gap moderate · Missing 2023 statements may change score.",
            "components": [
                {"label": "Signal Severity",    "val": 24, "max": 40},
                {"label": "Timing / Urgency",   "val": 16, "max": 25},
                {"label": "Financial Gap",      "val": 12, "max": 20},
                {"label": "Recovery Potential", "val":  9, "max": 15},
            ],
        },
        "signals": [
            {"name": "Crypto Exchange Activity",     "cat": "ASSET · CONVERSION",      "status": "none",     "count":  0, "amount": None},
            {"name": "Crypto Payment Gateways",      "cat": "CONVERSION",               "status": "none",     "count":  0, "amount": None},
            {"name": "Mortgage Servicer Activity",   "cat": "ASSET",                    "status": "detected", "count":  8, "amount": "$28,800"},
            {"name": "Gambling Platforms",           "cat": "CONVERSION · OBFUSCATION", "status": "none",     "count":  0, "amount": None},
            {"name": "Luxury Asset Merchants",       "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Travel Vendors",               "cat": "FLOW · LIFESTYLE",         "status": "none",     "count":  0, "amount": None},
            {"name": "Property Tax Authorities",     "cat": "ASSET",                    "status": "detected", "count":  1, "amount":  "$4,200"},
            {"name": "Storage Facilities",           "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Second Household Indicators",  "cat": "ASSET",                    "status": "possible", "count":  0, "amount": None},
            {"name": "Structuring / Cash Behaviour", "cat": "OBFUSCATION",              "status": "none",     "count":  0, "amount": None},
            {"name": "Recurring Unnamed Transfers",  "cat": "FLOW · OBFUSCATION",       "status": "detected", "count":  6, "amount": "$18,600"},
            {"name": "DeFi Platforms",               "cat": "ASSET · CONVERSION",       "status": "none",     "count":  0, "amount": None},
            {"name": "Rental Platforms",             "cat": "ASSET · FLOW",             "status": "detected", "count":  4, "amount": "$11,200"},
            {"name": "Gold & Precious Metals",       "cat": "ASSET",                    "status": "none",     "count":  0, "amount": None},
            {"name": "Gift Card / Prepaid",          "cat": "OBFUSCATION",              "status": "none",     "count":  0, "amount": None},
            {"name": "Cross-Border Value Transfer",  "cat": "FLOW",                     "status": "none",     "count":  0, "amount": None},
        ],
        "intel": [
            {
                "cat": "ASSET", "cat_cls": "asset",
                "title": "Undisclosed Investment Property",
                "narrative": "8 regular mortgage payments ($28,800) to ANZ Home Loans and council rates ($4,200) not attributable to the disclosed primary residence. Consistent with an undisclosed investment property.",
                "rec": "High Recovery", "rec_cls": "high",
                "tier": "Domestic Asset",
                "path": "Land title search in all states. Cross-reference ATO rental income schedule from tax records. Request ANZ loan file and security property address.",
            },
            {
                "cat": "ASSET · FLOW", "cat_cls": "asset",
                "title": "Rental Platform Income",
                "narrative": "4 inbound transfers from Airbnb and Stayz totalling $11,200. Rental income not disclosed in separation agreement financial statement.",
                "rec": "Medium Recovery", "rec_cls": "medium",
                "tier": "Short-Term Rental Platforms",
                "path": "Subpoena Airbnb and Stayz for full hosting history, property address, and earnings records. Cross-reference against asset disclosure.",
            },
        ],
        "verify_plus_teaser": {"available": False},
    },
    4: {
        "matter_id": 4,
        "run_at": "2026-03-15T16:05:00+00:00",
        "exposure": "LOW",
        "att": "green",
        "att_flag": "",
        "las": {
            "score": 22,
            "verdict": "LOW URGENCY",
            "verdict_cls": "low",
            "reason": "Limited signals · No crypto activity · Income gap within normal range.",
            "components": [
                {"label": "Signal Severity",    "val":  8, "max": 40},
                {"label": "Timing / Urgency",   "val":  7, "max": 25},
                {"label": "Financial Gap",      "val":  5, "max": 20},
                {"label": "Recovery Potential", "val":  2, "max": 15},
            ],
        },
        "signals": [
            {"name": "Crypto Exchange Activity",     "cat": "ASSET · CONVERSION",      "status": "none", "count": 0, "amount": None},
            {"name": "Crypto Payment Gateways",      "cat": "CONVERSION",               "status": "none", "count": 0, "amount": None},
            {"name": "Mortgage Servicer Activity",   "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Gambling Platforms",           "cat": "CONVERSION · OBFUSCATION", "status": "none", "count": 0, "amount": None},
            {"name": "Luxury Asset Merchants",       "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Travel Vendors",               "cat": "FLOW · LIFESTYLE",         "status": "none", "count": 0, "amount": None},
            {"name": "Property Tax Authorities",     "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Storage Facilities",           "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Second Household Indicators",  "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Structuring / Cash Behaviour", "cat": "OBFUSCATION",              "status": "none", "count": 0, "amount": None},
            {"name": "Recurring Unnamed Transfers",  "cat": "FLOW · OBFUSCATION",       "status": "none", "count": 0, "amount": None},
            {"name": "DeFi Platforms",               "cat": "ASSET · CONVERSION",       "status": "none", "count": 0, "amount": None},
            {"name": "Rental Platforms",             "cat": "ASSET · FLOW",             "status": "none", "count": 0, "amount": None},
            {"name": "Gold & Precious Metals",       "cat": "ASSET",                    "status": "none", "count": 0, "amount": None},
            {"name": "Gift Card / Prepaid",          "cat": "OBFUSCATION",              "status": "none", "count": 0, "amount": None},
            {"name": "Cross-Border Value Transfer",  "cat": "FLOW",                     "status": "none", "count": 0, "amount": None},
        ],
        "intel": [],
        "verify_plus_teaser": {"available": False},
    },
}


def seed_demo_data(db):
    """Insert demo matters and results if the DB is empty."""
    from .models import Matter, AnalysisResult
    if db.query(Matter).count() > 0:
        return  # Already seeded

    for m_data in DEMO_MATTERS:
        matter = Matter(**{k: v for k, v in m_data.items() if k != "id"})
        db.add(matter)
    db.flush()

    # Re-query to get assigned IDs (auto-increment may differ from seed IDs)
    matters = db.query(Matter).order_by(Matter.id).all()
    result_list = list(DEMO_RESULTS.values())
    for matter, result_data in zip(matters, result_list):
        result_data["matter_id"] = matter.id
        ar = AnalysisResult(matter_id=matter.id, result_json=json.dumps(result_data))
        db.add(ar)
    db.commit()
